### ISSUE TITLE
.PNG files will not open in diff tool using P4Merge

### ISSUE THREAD

**Issue by kyleherzog** [VerifyTests/DiffEngine#493]
* DiffEngineTray Version: 15.4.1+31aba5a7d6362b4f02f723cb7699af64dc41cbf4
 * OS: Microsoft Windows NT 10.0.22621.0

When trying to open .PNG file changes in diff tool with Helix P4Merge (2024 April 30 Rev. P4Merge/NTX64/2024.1/2591061) installed I get the following error: "Image files can not be merged".   Text files work fine.  If I manually enter the paths of my .png files in the P4Merge UI that works fine as well.

**Comment by kyleherzog** [comment]
I have upgraded to  DiffEngineTray Version: 15.4.2+b738f35b8aa6f311a16eb04ba4b697b63da4028e.  When I run my test that results in a different .png file, I still get the popup that says "Image files can not be merged" (maybe this is what I need to wait for the next version of Verify for?)  However, even if I right click on the DiffEngineTray, click the name of the .png file and then click Open diff tool, I get the same error message.

**Comment by SimonCropp** [comment]
@kyleherzog  DiffEngine ships as two parts.  DiffEngineTray the dotnet tool (the server). and  DiffEngine the nuget (the client). so it should have been fixed in DiffEngine the nuget, which i imagine u would need to add an explicit reference for.

however i just shipped version 25 of Verify. so updating to that should fix it for u without an explicit reference to DiffEngine

**Comment by kyleherzog** [comment]
Just pulled in Verify 25.  Works perfectly now. Thanks!
